(defun find-largest (list-of-numbers)
	(let ((largest (first list-of-numbers)))
		(dolist (element (rest list-of-numbers)
					largest)
			(when (> element largest)
				(setf largest element)))))

(defun fl-do* (list-of-numbers)
		(do* ((largest (first list-of-numbers)) 
			  (x list-of-numbers (rest x))
		  	  (element (first x) (first x)))
		 	 ((null x) largest)
		 		(when (> element largest)
		 			(setf largest element))))